/** @type {import("prettier").Config} */
module.exports = {
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  printWidth: 80,
  semi: false,
  arrowParens: 'always',
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  proseWrap: 'never',
  singleAttributePerLine: true,
  bracketSpacing: true,
  bracketSameLine: false,
  experimentalTernaries: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'css'],
  importOrder: [
    '^(await)',
    '^(if)',
    '^@/bootstrap/gesture-handler',
    '^expo-dev-client',
    '^@expo/metro-runtime',
    '^@/bootstrap(/.*)$',
    '',
    '^(@react|react)?(/.*)$',
    '^(@expo|expo)?(/.*)$',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/assets/(.*)$',
    '^@/lib/(.*)$',
    '^@/utils/(.*)$',
    '',
    '^@/state/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/(.*)$',
    '',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
    '',
    '^[./]',
  ],
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
  ],
}
